const VERSION = '0.1.0';
const CORS = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization,Mcp-Session-Id'};
const DEFAULT_BATCH_FILES = 25;
const DEFAULT_BATCH_BYTES = 250000;
const BINARY_EXTENSIONS = new Set(['png','jpg','jpeg','gif','webp','ico','woff','woff2','ttf','eot','pdf','zip','tar','gz','br','wasm','bin','exe','dll','so','dylib','mp4','mp3','wav','ogg','mov','avi']);
const TOOLS = [
  {name:'clone_status',description:'Health check. Returns version, binding status, active session count.',inputSchema:{type:'object',properties:{},required:[]}},
  {name:'plan_zip_clone',description:'Plans a chunked clone from source repo/path to destination. Builds manifest, assigns batches. Does NOT write to destination. Returns session_id.',inputSchema:{type:'object',properties:{src_owner:{type:'string'},src_repo:{type:'string'},src_ref:{type:'string'},src_path:{type:'string'},dst_owner:{type:'string'},dst_repo:{type:'string'},dst_branch:{type:'string'},dst_path:{type:'string'},include_paths:{type:'array',items:{type:'string'}},exclude_paths:{type:'array',items:{type:'string'}},replacements:{type:'array',items:{type:'object'}},batch_max_files:{type:'number'},batch_max_bytes:{type:'number'},skip_binary:{type:'boolean'},write_receipt:{type:'boolean'}},required:['src_owner','src_repo','dst_owner','dst_repo']}},
  {name:'run_zip_clone_batch',description:'Processes one batch. Fetches files, applies replacements, commits to destination.',inputSchema:{type:'object',properties:{session_id:{type:'string'},batch_index:{type:'number'},confirm_write:{type:'boolean'}},required:['session_id','batch_index']}},
  {name:'resume_zip_clone',description:'Resumes from first incomplete batch. Safe to call repeatedly after timeouts.',inputSchema:{type:'object',properties:{session_id:{type:'string'},confirm_write:{type:'boolean'},max_batches:{type:'number'}},required:['session_id']}},
  {name:'verify_zip_clone',description:'Verifies clone by comparing source manifest to destination. Reports mismatches.',inputSchema:{type:'object',properties:{session_id:{type:'string'}},required:['session_id']}},
  {name:'clone_receipt',description:'Returns full structured receipt for a clone session.',inputSchema:{type:'object',properties:{session_id:{type:'string'}},required:['session_id']}}
];
function rpc(id,r){return Response.json({jsonrpc:'2.0',id,result:r},{headers:CORS});}
function errResp(id,c,m){return Response.json({jsonrpc:'2.0',id,error:{code:c,message:m}},{headers:CORS});}
function tool(id,r){return rpc(id,{content:[{type:'text',text:JSON.stringify(r,null,2)}]});}
function genSessionId(){return 'gs_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
function isBinary(path){return BINARY_EXTENSIONS.has(path.split('.').pop().toLowerCase());}
function applyReplacements(content,replacements){if(!replacements||!replacements.length)return content;let r=content;for(const rep of replacements){if(rep.from&&rep.to)r=r.split(rep.from).join(rep.to);}return r;}
function shouldExclude(path,ex){for(const e of ex){if(path.includes(e))return true;}return false;}
function shouldInclude(path,inc){if(!inc||!inc.length)return true;for(const i of inc){if(path.startsWith(i))return true;}return false;}
async function ghGet(token,owner,repo,path,ref){const url='https://api.github.com/repos/'+owner+'/'+repo+'/contents/'+encodeURIComponent(path)+(ref?'?ref='+ref:'');const res=await fetch(url,{headers:{'Authorization':'Bearer '+token,'Accept':'application/vnd.github+json','User-Agent':'afo-gitzip-clone-mcp/'+VERSION}});if(!res.ok)throw new Error('GH GET '+path+' '+res.status+': '+await res.text());return res.json();}
async function ghGetRaw(token,owner,repo,path,ref){const url='https://api.github.com/repos/'+owner+'/'+repo+'/contents/'+encodeURIComponent(path)+(ref?'?ref='+ref:'');const res=await fetch(url,{headers:{'Authorization':'Bearer '+token,'Accept':'application/vnd.github.raw+json','User-Agent':'afo-gitzip-clone-mcp/'+VERSION}});if(!res.ok)throw new Error('GH raw '+path+' '+res.status);return res.text();}
async function ghPut(token,owner,repo,path,content,message,branch,sha){const url='https://api.github.com/repos/'+owner+'/'+repo+'/contents/'+encodeURIComponent(path);const body={message,content:btoa(unescape(encodeURIComponent(content))),branch:branch||'main'};if(sha)body.sha=sha;const res=await fetch(url,{method:'PUT',headers:{'Authorization':'Bearer '+token,'Accept':'application/vnd.github+json','Content-Type':'application/json','User-Agent':'afo-gitzip-clone-mcp/'+VERSION},body:JSON.stringify(body)});if(!res.ok)throw new Error('GH PUT '+path+' '+res.status+': '+await res.text());return res.json();}
async function ghGetSha(token,owner,repo,path,branch){try{const d=await ghGet(token,owner,repo,path,branch);return Array.isArray(d)?null:(d.sha||null);}catch{return null;}}
async function ghListRecursive(token,owner,repo,path,ref,exclude,depth){if(depth>10)return[];const items=await ghGet(token,owner,repo,path||'',ref);if(!Array.isArray(items))return[];const files=[];for(const item of items){if(shouldExclude(item.path,exclude))continue;if(item.type==='file')files.push({path:item.path,size:item.size,sha:item.sha});else if(item.type==='dir'){const sub=await ghListRecursive(token,owner,repo,item.path,ref,exclude,depth+1);files.push(...sub);}}return files;}
async function dbRun(db,sql,p){const s=db.prepare(sql);return p?s.bind(...p).run():s.run();}
async function dbFirst(db,sql,p){const s=db.prepare(sql);return p?s.bind(...p).first():s.first();}
async function dbAll(db,sql,p){const s=db.prepare(sql);const r=p?await s.bind(...p).all():await s.all();return r.results||[];}
async function ensureSchema(db){await dbRun(db,`CREATE TABLE IF NOT EXISTS clone_sessions (session_id TEXT PRIMARY KEY,src_owner TEXT,src_repo TEXT,src_ref TEXT,src_path TEXT,dst_owner TEXT,dst_repo TEXT,dst_branch TEXT,dst_path TEXT,replacements TEXT,include_paths TEXT,exclude_paths TEXT,batch_max_files INTEGER,batch_max_bytes INTEGER,skip_binary INTEGER,write_receipt INTEGER,source_commit_sha TEXT,file_count INTEGER,total_bytes INTEGER,batch_count INTEGER,status TEXT DEFAULT 'planned',created_at TEXT,updated_at TEXT)`);await dbRun(db,`CREATE TABLE IF NOT EXISTS clone_batches (session_id TEXT,batch_index INTEGER,file_count INTEGER,byte_count INTEGER,status TEXT DEFAULT 'pending',commit_sha TEXT,error TEXT,created_at TEXT,updated_at TEXT,PRIMARY KEY(session_id,batch_index))`);await dbRun(db,`CREATE TABLE IF NOT EXISTS clone_files (session_id TEXT,file_path TEXT,dst_path TEXT,size INTEGER,batch_index INTEGER,is_binary INTEGER,status TEXT DEFAULT 'pending',sha TEXT,PRIMARY KEY(session_id,file_path))`);}
async function handle(name,args,env){
  if(name==='clone_status'){let dbOk=false;let active=0;try{await ensureSchema(env.DB);const r=await dbFirst(env.DB,"SELECT COUNT(*) as n FROM clone_sessions WHERE status!='complete'");active=r?r.n:0;dbOk=true;}catch{}return{status:'ok',worker:'afo-gitzip-clone-mcp',version:VERSION,bindings:{GITHUB_TOKEN:!!env.GITHUB_TOKEN,DB:dbOk},active_sessions:active,default_batch_files:DEFAULT_BATCH_FILES,default_batch_bytes:DEFAULT_BATCH_BYTES,tools:TOOLS.map(function(t){return t.name;})};}
  if(name==='plan_zip_clone'){
    const{src_owner,src_repo,dst_owner,dst_repo}=args;if(!src_owner||!src_repo||!dst_owner||!dst_repo)throw new Error('src_owner,src_repo,dst_owner,dst_repo required');
    const src_ref=args.src_ref||'main';const src_path=args.src_path||'';const dst_branch=args.dst_branch||'main';const dst_path=args.dst_path!==undefined?args.dst_path:src_path;const replacements=args.replacements||[];const include_paths=args.include_paths||[];const exclude_paths=args.exclude_paths||['node_modules','.wrangler','dist','build','.git'];const batch_max_files=args.batch_max_files||DEFAULT_BATCH_FILES;const batch_max_bytes=args.batch_max_bytes||DEFAULT_BATCH_BYTES;const skip_binary=args.skip_binary!==false;const write_receipt=args.write_receipt!==false;
    await ensureSchema(env.DB);
    let source_commit_sha='unknown';try{const r=await fetch('https://api.github.com/repos/'+src_owner+'/'+src_repo+'/git/ref/heads/'+src_ref,{headers:{'Authorization':'Bearer '+env.GITHUB_TOKEN,'Accept':'application/vnd.github+json','User-Agent':'afo-gitzip-clone-mcp/'+VERSION}});if(r.ok){const j=await r.json();source_commit_sha=j.object&&j.object.sha?j.object.sha:'unknown';}}catch{}
    const allFiles=await ghListRecursive(env.GITHUB_TOKEN,src_owner,src_repo,src_path,src_ref,exclude_paths,0);const skipped=[];const toClone=[];
    for(const f of allFiles){if(!shouldInclude(f.path,include_paths)){skipped.push({path:f.path,reason:'not_in_include_paths'});continue;}if(skip_binary&&isBinary(f.path)){skipped.push({path:f.path,reason:'binary_skipped',size:f.size});continue;}toClone.push(f);}
    const batches=[];let cur=[];let curBytes=0;for(const f of toClone){if(cur.length>=batch_max_files||(curBytes+f.size>batch_max_bytes&&cur.length>0)){batches.push(cur);cur=[];curBytes=0;}cur.push(f);curBytes+=f.size;}if(cur.length>0)batches.push(cur);
    const session_id=genSessionId();const now=new Date().toISOString();
    await dbRun(env.DB,'INSERT INTO clone_sessions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[session_id,src_owner,src_repo,src_ref,src_path,dst_owner,dst_repo,dst_branch,dst_path,JSON.stringify(replacements),JSON.stringify(include_paths),JSON.stringify(exclude_paths),batch_max_files,batch_max_bytes,skip_binary?1:0,write_receipt?1:0,source_commit_sha,toClone.length,toClone.reduce(function(s,f){return s+f.size;},0),batches.length,'planned',now,now]);
    for(let i=0;i<batches.length;i++){const b=batches[i];await dbRun(env.DB,'INSERT INTO clone_batches VALUES (?,?,?,?,?,?,?,?,?)',[session_id,i,b.length,b.reduce(function(s,f){return s+f.size;},0),'pending',null,null,now,now]);for(const f of b){const rel=src_path?f.path.slice(src_path.length).replace(/^\//,''):f.path;const dstFp=dst_path?dst_path+'/'+rel:f.path;await dbRun(env.DB,'INSERT OR IGNORE INTO clone_files VALUES (?,?,?,?,?,?,?,?)',[session_id,f.path,dstFp,f.size,i,isBinary(f.path)?1:0,'pending',f.sha]);}}
    return{ok:true,session_id,source:src_owner+'/'+src_repo+'@'+src_ref+(src_path?':'+src_path:''),destination:dst_owner+'/'+dst_repo+'@'+dst_branch+(dst_path?':'+dst_path:''),source_commit_sha,file_count:toClone.length,total_bytes:toClone.reduce(function(s,f){return s+f.size;},0),batch_count:batches.length,skipped_files:skipped.length,skipped_sample:skipped.slice(0,5),planned_batches:batches.map(function(b,i){return{batch_index:i,files:b.length,bytes:b.reduce(function(s,f){return s+f.size;},0)};}),warnings:batches.length===0?['No files found. Check src_path and exclude_paths.']:[],next_step:'Run resume_zip_clone with session_id: '+session_id+' and confirm_write: true'};
  }
  if(name==='run_zip_clone_batch'){
    const{session_id,batch_index}=args;if(!session_id)throw new Error('session_id required');if(batch_index===undefined)throw new Error('batch_index required');const confirmWrite=args.confirm_write===true;
    await ensureSchema(env.DB);const session=await dbFirst(env.DB,'SELECT * FROM clone_sessions WHERE session_id = ?',[session_id]);if(!session)throw new Error('Session not found: '+session_id);const batch=await dbFirst(env.DB,'SELECT * FROM clone_batches WHERE session_id = ? AND batch_index = ?',[session_id,batch_index]);if(!batch)throw new Error('Batch '+batch_index+' not found');
    if(batch.status==='complete')return{ok:true,session_id,batch_index,status:'already_complete',commit_sha:batch.commit_sha,message:'Batch already committed.'};
    const files=await dbAll(env.DB,'SELECT * FROM clone_files WHERE session_id = ? AND batch_index = ?',[session_id,batch_index]);if(!files.length)return{ok:true,session_id,batch_index,files_written:0,message:'No files in batch.'};
    const replacements=JSON.parse(session.replacements||'[]');const written=[];const skipped=[];const errors=[];let lastCommitSha=null;
    for(const f of files){if(f.status==='committed'){skipped.push({path:f.dst_path,reason:'already_committed'});continue;}if(f.is_binary){skipped.push({path:f.file_path,reason:'binary'});continue;}try{const raw=await ghGetRaw(env.GITHUB_TOKEN,session.src_owner,session.src_repo,f.file_path,session.src_ref);const patched=applyReplacements(raw,replacements);if(confirmWrite){const existingSha=await ghGetSha(env.GITHUB_TOKEN,session.dst_owner,session.dst_repo,f.dst_path,session.dst_branch);const result=await ghPut(env.GITHUB_TOKEN,session.dst_owner,session.dst_repo,f.dst_path,patched,'gitzip-clone: '+session_id+' batch '+batch_index+' -- '+f.dst_path,session.dst_branch,existingSha);lastCommitSha=result.commit&&result.commit.sha?result.commit.sha:lastCommitSha;await dbRun(env.DB,'UPDATE clone_files SET status = ? WHERE session_id = ? AND file_path = ?',['committed',session_id,f.file_path]);written.push(f.dst_path);}else{written.push({path:f.dst_path,dry_run:true,bytes:patched.length});}}catch(e){errors.push({path:f.file_path,error:e.message});await dbRun(env.DB,'UPDATE clone_files SET status = ? WHERE session_id = ? AND file_path = ?',['error',session_id,f.file_path]);}}
    const now=new Date().toISOString();if(confirmWrite&&errors.length===0)await dbRun(env.DB,'UPDATE clone_batches SET status=?,commit_sha=?,updated_at=? WHERE session_id=? AND batch_index=?',['complete',lastCommitSha,now,session_id,batch_index]);else if(errors.length>0)await dbRun(env.DB,'UPDATE clone_batches SET status=?,error=?,updated_at=? WHERE session_id=? AND batch_index=?',['error',JSON.stringify(errors),now,session_id,batch_index]);
    const remaining=await dbAll(env.DB,"SELECT batch_index FROM clone_batches WHERE session_id = ? AND status != 'complete'",[session_id]);const allDone=remaining.length===0;if(allDone&&confirmWrite)await dbRun(env.DB,'UPDATE clone_sessions SET status=?,updated_at=? WHERE session_id=?',['complete',now,session_id]);
    const nextBatch=remaining.filter(function(r){return r.batch_index>batch_index;});
    return{ok:errors.length===0,session_id,batch_index,committed:confirmWrite&&errors.length===0,commit_sha:lastCommitSha,files_written:written.length,files_skipped:skipped.length,errors,next_batch_index:nextBatch.length>0?nextBatch[0].batch_index:null,clone_complete:allDone};
  }
  if(name==='resume_zip_clone'){
    const{session_id}=args;if(!session_id)throw new Error('session_id required');const confirmWrite=args.confirm_write===true;const maxBatches=args.max_batches||3;
    await ensureSchema(env.DB);const session=await dbFirst(env.DB,'SELECT * FROM clone_sessions WHERE session_id = ?',[session_id]);if(!session)throw new Error('Session not found: '+session_id);if(session.status==='complete')return{ok:true,session_id,status:'already_complete',message:'Clone already complete.'};
    const pending=await dbAll(env.DB,"SELECT batch_index FROM clone_batches WHERE session_id = ? AND status != 'complete' ORDER BY batch_index ASC",[session_id]);if(!pending.length){await dbRun(env.DB,'UPDATE clone_sessions SET status=?,updated_at=? WHERE session_id=?',['complete',new Date().toISOString(),session_id]);return{ok:true,session_id,status:'complete',message:'All batches complete.'};}
    const toRun=pending.slice(0,maxBatches);const batchResults=[];for(const b of toRun){const r=await handle('run_zip_clone_batch',{session_id,batch_index:b.batch_index,confirm_write:confirmWrite},env);batchResults.push(r);if(r.errors&&r.errors.length>0)break;}
    const stillPending=await dbAll(env.DB,"SELECT batch_index FROM clone_batches WHERE session_id = ? AND status != 'complete' ORDER BY batch_index ASC",[session_id]);
    return{ok:batchResults.every(function(r){return r.ok;}),session_id,batches_processed:batchResults.length,batches_remaining:stillPending.length,batch_results:batchResults,clone_complete:stillPending.length===0,next_step:stillPending.length>0?'Call resume_zip_clone again. Batches remaining: '+stillPending.length:'Clone complete. Run verify_zip_clone.'};
  }
  if(name==='verify_zip_clone'){
    const{session_id}=args;if(!session_id)throw new Error('session_id required');await ensureSchema(env.DB);const session=await dbFirst(env.DB,'SELECT * FROM clone_sessions WHERE session_id = ?',[session_id]);if(!session)throw new Error('Session not found: '+session_id);
    const allFiles=await dbAll(env.DB,'SELECT * FROM clone_files WHERE session_id = ?',[session_id]);const batches=await dbAll(env.DB,'SELECT * FROM clone_batches WHERE session_id = ?',[session_id]);
    const committed=allFiles.filter(function(f){return f.status==='committed';});const errors=allFiles.filter(function(f){return f.status==='error';});const pending=allFiles.filter(function(f){return f.status==='pending';});const binary=allFiles.filter(function(f){return f.is_binary;});
    const spotChecks=[];for(const f of committed.slice(0,5)){try{await ghGet(env.GITHUB_TOKEN,session.dst_owner,session.dst_repo,f.dst_path,session.dst_branch);spotChecks.push({path:f.dst_path,ok:true});}catch(e){spotChecks.push({path:f.dst_path,ok:false,error:e.message});}}
    return{ok:errors.length===0&&pending.length===0,session_id,session_status:session.status,source:session.src_owner+'/'+session.src_repo,destination:session.dst_owner+'/'+session.dst_repo,total_planned:allFiles.length,committed:committed.length,errors:errors.length,pending:pending.length,binary_skipped:binary.length,spot_checks:spotChecks,batch_summary:batches.map(function(b){return{batch_index:b.batch_index,status:b.status,commit_sha:b.commit_sha,files:b.file_count};}),verdict:errors.length===0&&pending.length===0?'PASS: All files committed.':'FAIL: '+errors.length+' errors, '+pending.length+' pending. Run resume_zip_clone to continue.'};
  }
  if(name==='clone_receipt'){
    const{session_id}=args;if(!session_id)throw new Error('session_id required');await ensureSchema(env.DB);const session=await dbFirst(env.DB,'SELECT * FROM clone_sessions WHERE session_id = ?',[session_id]);if(!session)throw new Error('Session not found: '+session_id);
    const batches=await dbAll(env.DB,'SELECT * FROM clone_batches WHERE session_id = ? ORDER BY batch_index ASC',[session_id]);const allFiles=await dbAll(env.DB,'SELECT * FROM clone_files WHERE session_id = ?',[session_id]);
    const committed=allFiles.filter(function(f){return f.status==='committed';});const errFiles=allFiles.filter(function(f){return f.status==='error';});const pending=allFiles.filter(function(f){return f.status==='pending';});const binaries=allFiles.filter(function(f){return f.is_binary;});
    return{session_id,status:session.status,source:{owner:session.src_owner,repo:session.src_repo,ref:session.src_ref,path:session.src_path,commit_sha:session.source_commit_sha},destination:{owner:session.dst_owner,repo:session.dst_repo,branch:session.dst_branch,path:session.dst_path},replacements:JSON.parse(session.replacements||'[]'),include_paths:JSON.parse(session.include_paths||'[]'),exclude_paths:JSON.parse(session.exclude_paths||'[]'),stats:{files_planned:allFiles.length,files_committed:committed.length,files_errored:errFiles.length,files_pending:pending.length,binary_skipped:binaries.length,total_bytes:session.total_bytes,batch_count:session.batch_count},destination_commits:batches.filter(function(b){return b.commit_sha;}).map(function(b){return b.commit_sha;}),failed_files:errFiles.map(function(f){return{path:f.file_path,dst:f.dst_path};}),batch_summary:batches.map(function(b){return{index:b.batch_index,status:b.status,files:b.file_count,commit_sha:b.commit_sha};}),created_at:session.created_at,updated_at:session.updated_at};
  }
  throw new Error('Unknown tool: '+name);
}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const url=new URL(request.url);if(url.pathname==='/health')return Response.json({status:'ok',worker:'afo-gitzip-clone-mcp',version:VERSION},{headers:CORS});if(request.method!=='POST')return new Response('not found',{status:404,headers:CORS});let body;try{body=await request.json();}catch{return errResp(null,-32700,'Parse error');}const{id,method,params}=body;if(method==='initialize')return rpc(id,{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'afo-gitzip-clone-mcp',version:VERSION}});if(method==='notifications/initialized')return new Response(null,{status:204,headers:CORS});if(method==='ping')return rpc(id,{});if(method==='tools/list')return rpc(id,{tools:TOOLS});if(method==='tools/call'){try{return tool(id,await handle(params?.name,params?.arguments||{},env));}catch(e){return errResp(id,-32603,'Tool error: '+e.message);}}return errResp(id,-32601,'Method not found: '+method);}};
