const VERSION='0.2.0-core';
const METHODS=['zip.status','zip.tools','zip.plan','zip.execute','zip.receipt','zip.rollback','zip.repo.writeFile','zip.repo.writeBatch','zip.repo.planPatch','zip.repo.applyPatch','zip.repo.applyPatchBatch','zip.clone.plan','zip.clone.runBatch','zip.clone.resume','zip.clone.verify','zip.clone.receipt','zip.artifact.list','zip.artifact.get','zip.artifact.put','zip.artifact.delete','zip.artifact.head','zip.artifact.presign'];
export default{async fetch(req,env,ctx){try{const u=new URL(req.url);if(req.method==='OPTIONS')return cors(new Response(null,{status:204}));if(req.method==='GET')return json(u.pathname==='/status'?await status(env):tools(env));if(req.method==='POST'&&['/','/rpc','/mcp'].includes(u.pathname)){const b=await req.json().catch(()=>null);return json(Array.isArray(b)?await Promise.all(b.map(x=>rpc(x,env,ctx))):await rpc(b,env,ctx));}return json({ok:false,error:'not_found'},404);}catch(e){return json({ok:false,error:e.message||String(e)},500)}}};
async function rpc(c,env,ctx){const id=c&&'id'in c?c.id:null;try{if(!c||c.jsonrpc!=='2.0'||!c.method)return err(id,-32600,'Invalid JSON-RPC request');return{jsonrpc:'2.0',id,result:await run(c.method,c.params||{},env,ctx)}}catch(e){return err(id,e.code||-32000,e.message||String(e),e.details)}}
function err(id,code,message,data){return{jsonrpc:'2.0',id,error:{code,message,...(data?{data}:{})}}}
async function run(m,p,env,ctx){if(!METHODS.includes(m))throw E('Unknown method '+m,-32601);if(m==='zip.status')return status(env);if(m==='zip.tools')return tools(env);if(m==='zip.plan')return plan(p,env);if(m==='zip.execute')return run(req(p,'method'),p.params||{},env,ctx);if(m==='zip.repo.writeFile')return write({...p,files:[{path:req(p,'path'),content:req(p,'content')} ]},env,ctx,m);if(m==='zip.repo.writeBatch')return write(p,env,ctx,m);if(m==='zip.repo.planPatch')return planPatch(p);if(m==='zip.repo.applyPatch')return applyPatch(p,env,ctx);if(m.startsWith('zip.artifact.'))return artifact(m,p,env,ctx);if(m==='zip.receipt')return receipt(p,env);return{method:m,ok:m.includes('clone.plan'),status:'delegated',reason:'v2 core exposes this namespace; route clone/batch/rollback advanced execution to the existing Zip engines until v2.1.'}}
async function status(env){return{method:'zip.status',ok:true,name:'afo-zip-gateway-v2',version:VERSION,jsonrpc:'2.0',dry_run_default:env.ZIP_DRY_RUN_DEFAULT!=='false',write_enabled:env.ZIP_WRITE_ENABLED==='true',delete_enabled:env.ZIP_DELETE_ENABLED==='true',default_owner:env.DEFAULT_OWNER||null,default_branch:env.DEFAULT_BRANCH||'main',bindings:{github_token:!!env.GITHUB_TOKEN,r2_native:!!bucket(env)},methods:METHODS}}
function tools(env){return{method:'zip.tools',ok:true,name:'afo-zip-gateway-v2',version:VERSION,transport:'json-rpc-2.0',auth:'private-worker-secrets-no-user-oauth',dry_run_default:env.ZIP_DRY_RUN_DEFAULT!=='false',methods:METHODS}}
function plan(p,env){const t=String(p.intent||p.task||'').toLowerCase();let s='zip.tools';if(t.includes('patch')||t.includes('edit'))s='zip.repo.applyPatch';else if(t.includes('batch'))s='zip.repo.writeBatch';else if(t.includes('write')||t.includes('create'))s='zip.repo.writeFile';else if(t.includes('clone'))s='zip.clone.plan';else if(t.includes('artifact')||t.includes('r2'))s='zip.artifact.put';return{method:'zip.plan',ok:true,selected_method:s,dry_run_default:env.ZIP_DRY_RUN_DEFAULT!=='false',proposed_call:{jsonrpc:'2.0',id:'rpc_'+crypto.randomUUID(),method:s,params:p.params||{}}}}
async function write(p,env,ctx,method){const t=T(p,env),files=req(p,'files');own(t.owner,env);if(!Array.isArray(files)||!files.length)throw E('files must be non-empty',-32602);const dry=p.dry_run??env.ZIP_DRY_RUN_DEFAULT!=='false',sid=p.session_id||'zip_sess_'+crypto.randomUUID(),rid='zip_receipt_'+crypto.randomUUID();if(dry||!(p.confirm_write===true||env.ZIP_WRITE_ENABLED==='true')){const r=await rec(method,sid,rid,t,{dry_run:true,files:files.map(f=>f.path)},env,ctx);return{method,ok:true,dry_run:true,session_id:sid,receipt_id:rid,target:t,planned_files:files.length,receipt:r}}const commits=[];for(const f of files){const old=await safeRead(t,f.path,env);commits.push(await put(t,f.path,String(f.content),p.message||'zip: write '+f.path,env,old?.sha))}const r=await rec(method,sid,rid,t,{dry_run:false,commits},env,ctx);return{method,ok:true,dry_run:false,session_id:sid,receipt_id:rid,target:t,changed:{files:files.map(f=>f.path),commits},receipt:r}}
function planPatch(p){const out=patch(req(p,'content'),req(p,'operations')),ok=(p.verify||[]).every(v=>v.contains?out.includes(v.contains):v.not_contains?!out.includes(v.not_contains):true);return{method:'zip.repo.planPatch',ok,dry_run:true,content:p.return_content===false?undefined:out}}
async function applyPatch(p,env,ctx){const t=T(p,env),path=req(p,'path'),cur=await read(t,path,env),out=patch(cur.content,req(p,'operations')),dry=p.dry_run??env.ZIP_DRY_RUN_DEFAULT!=='false';if(dry||!(p.confirm_write===true||env.ZIP_WRITE_ENABLED==='true'))return{method:'zip.repo.applyPatch',ok:true,dry_run:true,target:t,path,content:p.return_content?out:undefined};const c=await put(t,path,out,p.message||'zip: patch '+path,env,cur.sha);const r=await rec('zip.repo.applyPatch',p.session_id||'zip_sess_'+crypto.randomUUID(),'zip_receipt_'+crypto.randomUUID(),t,{path,commit:c},env,ctx);return{method:'zip.repo.applyPatch',ok:true,dry_run:false,target:t,changed:{files:[path],commit:c},receipt:r}}
async function artifact(m,p,env,ctx){const b=needBucket(env),key=p.key;if(m==='zip.artifact.list'){const x=await b.list({prefix:p.prefix||'',limit:Number(p.limit||100)});return{method:m,ok:true,objects:x.objects.map(o=>({key:o.key,size:o.size,uploaded:o.uploaded}))}}if(m==='zip.artifact.get'){const o=await b.get(req(p,'key'));return o?{method:m,ok:true,key,size:o.size,content:await o.text()}:{method:m,ok:false,key,reason:'not_found'}}if(m==='zip.artifact.put'){await b.put(req(p,'key'),req(p,'content'),{httpMetadata:{contentType:p.content_type||'application/octet-stream'}});return{method:m,ok:true,key}}if(m==='zip.artifact.delete'){if(env.ZIP_DELETE_ENABLED!=='true'&&p.confirm_delete!==true)throw E('delete disabled',403);await b.delete(req(p,'key'));return{method:m,ok:true,key}}if(m==='zip.artifact.head'){const h=await b.head(req(p,'key'));return h?{method:m,ok:true,key,size:h.size,uploaded:h.uploaded}:{method:m,ok:false,key,reason:'not_found'}}return{method:m,ok:false,reason:'presign delegates to CloudZip R2 v1'}}
async function receipt(p,env){const b=needBucket(env);const sid=req(p,'session_id');const x=await b.list({prefix:`zip/receipts/${sid}/`,limit:Number(p.limit||100)});return{method:'zip.receipt',ok:true,session_id:sid,receipts:x.objects.map(o=>({key:o.key,size:o.size,uploaded:o.uploaded}))}}
async function rec(method,sid,rid,target,details,env,ctx){const r={ok:true,version:VERSION,method,session_id:sid,receipt_id:rid,target,details,created_at:new Date().toISOString(),receipt_key:`zip/receipts/${sid}/${rid}.json`};const b=bucket(env);if(b)ctx?.waitUntil?ctx.waitUntil(b.put(r.receipt_key,JSON.stringify(r,null,2),{httpMetadata:{contentType:'application/json'}})):await b.put(r.receipt_key,JSON.stringify(r,null,2),{httpMetadata:{contentType:'application/json'}});return r}
async function put(t,path,content,msg,env,sha){const body={message:msg,content:b64(content),branch:t.branch};if(sha)body.sha=sha;const d=await gh(env,'PUT',`/repos/${t.owner}/${t.repo}/contents/${enc(path)}`,body);return{sha:d.commit?.sha,path,url:d.content?.html_url}}
async function read(t,path,env){const d=await gh(env,'GET',`/repos/${t.owner}/${t.repo}/contents/${enc(path)}?ref=${encodeURIComponent(t.branch)}`);return{path,sha:d.sha,content:unb64(d.content||'')}}
async function safeRead(t,path,env){try{return await read(t,path,env)}catch(e){if(String(e.message).includes('GitHub 404'))return null;throw e}}
async function gh(env,method,path,body){if(!env.GITHUB_TOKEN)throw E('GITHUB_TOKEN not configured',500);const r=await fetch('https://api.github.com'+path,{method,headers:{Authorization:'Bearer '+env.GITHUB_TOKEN,Accept:'application/vnd.github+json','User-Agent':'afo-zip-gateway-v2',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const text=await r.text(),data=text?JSON.parse(text):null;if(!r.ok)throw E('GitHub '+r.status+': '+(data?.message||text),r.status,data);return data}
function patch(s,ops){let out=String(s);for(const op of ops){if((op.type||'replace')==='replace')out=out.replace(req(op,'old_text',op.find),req(op,'new_text',op.text));else if(op.type==='append')out+=req(op,'text');else if(op.type==='prepend')out=req(op,'text')+out;else throw E('unsupported patch op '+op.type,-32602)}return out}
function T(p,env){return{owner:p.owner||env.DEFAULT_OWNER,repo:req(p,'repo'),branch:p.branch||env.DEFAULT_BRANCH||'main'}}function req(o,k,f){const v=f!==undefined?f:o?.[k];if(v===undefined||v===null||v==='')throw E('missing '+k,-32602);return v}function own(o,env){const a=env.ZIP_ALLOWED_OWNER||env.DEFAULT_OWNER||'*';if(a!=='*'&&o!==a)throw E('owner not allowed',403)}function bucket(env){return env.ZIP_ARTIFACTS||env.ZIP_BUCKET||env.ARTIFACTS||null}function needBucket(env){const b=bucket(env);if(!b)throw E('R2 binding not configured',500);return b}function enc(p){return String(p).split('/').filter(Boolean).map(encodeURIComponent).join('/')}function b64(s){let bin='';for(const b of new TextEncoder().encode(String(s)))bin+=String.fromCharCode(b);return btoa(bin)}function unb64(s){const bin=atob(String(s).replace(/\s/g,''));return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0)))}function E(m,c=-32000,d){const e=new Error(m);e.code=c;e.details=d;return e}function json(x,s=200){return cors(new Response(JSON.stringify(x,null,2),{status:s,headers:{'content-type':'application/json'}}))}function cors(r){const h=new Headers(r.headers);h.set('Access-Control-Allow-Origin','*');h.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type, Authorization');return new Response(r.body,{status:r.status,headers:h})}
