const VERSION="0.1.0",WORKER_NAME="afo_github_state_mcp";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const TOOLS=["state_status","read_state_file","write_state_file","commit_state_bundle","list_state_tree","compare_state_versions"].map(name=>({name,description:`${name} for GitHub state plane.`,inputSchema:{type:"object",properties:{},required:[]}}));
function j(v,s=200){return Response.json(v,{status:s,headers:CORS})}function rr(id,result){return j({jsonrpc:"2.0",id,result})}function tr(id,result){return j({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result,null,2)}]}})}function er(id,c,m){return j({jsonrpc:"2.0",id,error:{code:c,message:m}})}function ep(p){return p.split("/").map(encodeURIComponent).join("/")}
async function gh(env,method,path,body){if(!env.GITHUB_TOKEN)throw new Error("GITHUB_TOKEN binding missing");const r=await fetch(`https://api.github.com${path}`,{method,headers:{Authorization:`Bearer ${env.GITHUB_TOKEN}`,"Content-Type":"application/json","User-Agent":WORKER_NAME,Accept:"application/vnd.github+json"},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();const x=t?JSON.parse(t):{};if(!r.ok)throw new Error(`GitHub HTTP ${r.status}: ${t}`);return x}
async function readFile(a,e){const owner=a.owner||e.DEFAULT_OWNER||"nothinginfinity",branch=a.branch||"main";const o=await gh(e,"GET",`/repos/${owner}/${a.repo}/contents/${ep(a.path)}?ref=${encodeURIComponent(branch)}`);return{owner,repo:a.repo,branch,path:a.path,sha:o.sha,content:decodeURIComponent(escape(atob(o.content.replace(/\n/g,""))))}}
async function writeFile(a,e){const owner=a.owner||e.DEFAULT_OWNER||"nothinginfinity",branch=a.branch||"main";let sha;try{sha=(await gh(e,"GET",`/repos/${owner}/${a.repo}/contents/${ep(a.path)}?ref=${encodeURIComponent(branch)}`)).sha}catch(_){}const out=await gh(e,"PUT",`/repos/${owner}/${a.repo}/contents/${ep(a.path)}`,{message:a.message||`Update ${a.path}`,content:btoa(unescape(encodeURIComponent(a.content))),branch,sha});return{ok:true,owner,repo:a.repo,branch,path:a.path,sha:out.content&&out.content.sha,commit_sha:out.commit&&out.commit.sha,html_url:out.commit&&out.commit.html_url}}
async function dispatch(n,a,e){if(n==="state_status")return{worker:WORKER_NAME,version:VERSION,status:"ok",plane:"github_state",bindings:{GITHUB_TOKEN:Boolean(e.GITHUB_TOKEN),DEFAULT_OWNER:Boolean(e.DEFAULT_OWNER)},tools:TOOLS.map(t=>t.name)};if(n==="read_state_file")return readFile(a,e);if(n==="write_state_file")return writeFile(a,e);if(n==="commit_state_bundle"){const results=[];for(const f of a.files||[])results.push(await writeFile({...a,...f},e));return{ok:true,count:results.length,results}}if(n==="list_state_tree"){const owner=a.owner||e.DEFAULT_OWNER||"nothinginfinity",branch=a.branch||"main",path=a.path||"";return gh(e,"GET",`/repos/${owner}/${a.repo}/contents/${ep(path)}?ref=${encodeURIComponent(branch)}`)}if(n==="compare_state_versions")return{changed:JSON.stringify(a.before)!==JSON.stringify(a.after),before_keys:Object.keys(a.before||{}),after_keys:Object.keys(a.after||{})};throw new Error(`Unknown tool: ${n}`)}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});if(request.method==="GET")return j({worker:WORKER_NAME,version:VERSION,status:"ok",tools:TOOLS.map(t=>t.name)});let p;try{p=await request.json()}catch{return er(null,-32700,"Invalid JSON")}const{id=null,method,params={}}=p;try{if(method==="initialize")return rr(id,{protocolVersion:"2024-11-05",serverInfo:{name:WORKER_NAME,version:VERSION},capabilities:{tools:{}}});if(method==="tools/list")return rr(id,{tools:TOOLS});if(method==="tools/call")return tr(id,await dispatch(params.name,params.arguments||{},env));return er(id,-32601,`Method not found: ${method}`)}catch(e){return er(id,-32603,`Tool error: ${e.message}`)}}};
