const VERSION="0.3.3";
const WORKER_NAME="afo-youtube-transcript-resilient-mcp";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,Mcp-Session-Id"};
const TOOLS=[
{name:"youtube_resilient_status",description:"Health check for the resilient transcript MCP.",inputSchema:{type:"object",properties:{},required:[]}},
{name:"get_browser_capture_helper",description:"Return helper page URL and instructions for pasting a visible YouTube transcript into this MCP.",inputSchema:{type:"object",properties:{url:{type:"string"}},required:[]}},
{name:"probe_youtube_sources",description:"Probe a video URL for visible public caption tracks.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},language:{type:"string",default:"en"}}}},
{name:"capture_youtube_transcript_resilient",description:"Capture visible public captions and store them.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},language:{type:"string",default:"en"},title:{type:"string"},force:{type:"boolean",default:false}}}},
{name:"submit_browser_caption_payload",description:"Import a transcript payload exported from a browser/helper.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},language:{type:"string",default:"en"},title:{type:"string"},payload_format:{type:"string",enum:["plain_text","json3","vtt","segments_json"],default:"plain_text"},text:{type:"string"},payload:{type:"string"},segments:{type:"array",items:{type:"object"}}}}},
{name:"import_transcript_text",description:"Manually import transcript text for a video URL.",inputSchema:{type:"object",required:["url","text"],properties:{url:{type:"string"},text:{type:"string"},language:{type:"string",default:"en"},title:{type:"string"},source_method:{type:"string",default:"manual_import"}}}},
{name:"create_audio_transcription_job",description:"Create a transcript job record for later completion.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},language:{type:"string",default:"en"},title:{type:"string"},audio_source_note:{type:"string"}}}},
{name:"submit_transcription_result",description:"Submit a completed transcript job result.",inputSchema:{type:"object",required:["job_id","text"],properties:{job_id:{type:"string"},text:{type:"string"},segments:{type:"array",items:{type:"object"}},title:{type:"string"},source_method:{type:"string",default:"external_transcription"},webhook_secret:{type:"string"}}}},
{name:"get_youtube_transcript_resilient",description:"Retrieve a stored transcript.",inputSchema:{type:"object",required:["transcript_id"],properties:{transcript_id:{type:"string"},include_text:{type:"boolean",default:true},include_segments:{type:"boolean",default:false}}}},
{name:"list_youtube_transcripts_resilient",description:"List stored transcript records.",inputSchema:{type:"object",properties:{limit:{type:"number",default:20},video_id:{type:"string"},language:{type:"string"}},required:[]}},
{name:"search_youtube_transcripts_resilient",description:"Keyword search stored transcripts.",inputSchema:{type:"object",required:["query"],properties:{query:{type:"string"},video_id:{type:"string"},top_k:{type:"number",default:8}}}},
{name:"summarize_youtube_transcript_resilient",description:"Summarize a stored transcript.",inputSchema:{type:"object",required:["transcript_id"],properties:{transcript_id:{type:"string"},max_chars:{type:"number",default:5000}}}}
];
function rpc(id,result){return Response.json({jsonrpc:"2.0",id,result},{headers:CORS})}
function errResp(id,code,message){return Response.json({jsonrpc:"2.0",id,error:{code,message}},{headers:CORS})}
function tool(id,result){return rpc(id,{content:[{type:"text",text:JSON.stringify(result,null,2)}]})}
function nowIso(){return new Date().toISOString()}
function newId(prefix){return prefix+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
async function run(db,sql,params=[]){return db.prepare(sql).bind(...params).run()}
async function first(db,sql,params=[]){return db.prepare(sql).bind(...params).first()}
async function all(db,sql,params=[]){const r=await db.prepare(sql).bind(...params).all();return r.results||[]}
async function kvPut(kv,key,value){await kv.put(key,typeof value==="string"?value:JSON.stringify(value))}
async function kvGet(kv,key){const v=await kv.get(key);if(v===null)return null;try{return JSON.parse(v)}catch{return v}}
async function schema(env){await run(env.DB,"CREATE TABLE IF NOT EXISTS youtube_transcripts_resilient (id TEXT PRIMARY KEY, video_id TEXT, url TEXT, title TEXT, language TEXT, source_method TEXT, text_kv_key TEXT, segments_kv_key TEXT, char_count INTEGER, chunk_count INTEGER, status TEXT, error TEXT, created_at TEXT, updated_at TEXT)");await run(env.DB,"CREATE TABLE IF NOT EXISTS transcript_jobs_resilient (job_id TEXT PRIMARY KEY, video_id TEXT, url TEXT, language TEXT, title TEXT, status TEXT, note TEXT, result_transcript_id TEXT, error TEXT, created_at TEXT, updated_at TEXT)")}
function videoId(input){try{const u=new URL(input);if(u.hostname.includes("youtu.be"))return u.pathname.split("/").filter(Boolean)[0]||null;if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/").filter(Boolean)[1]||null;return u.searchParams.get("v")}catch{const m=String(input).match(/(?:v=|youtu\.be\/|shorts\/)([A-Za-z0-9_-]{6,})/);return m?m[1]:null}}
function tracks(html){const m=html.match(/\"captionTracks\":(\[.*?\])\s*,\s*\"audioTracks\"/);if(!m)return[];try{return JSON.parse(m[1].replace(/\\u0026/g,"&"))}catch{return[]}}
function pickTrack(list,lang){return list.find(t=>t.languageCode===lang)||list.find(t=>String(t.languageCode||"").startsWith(String(lang).split("-")[0]))||list.find(t=>t.kind==="asr")||list[0]}
function fmtUrl(base,fmt){const u=new URL(base);u.searchParams.set("fmt",fmt);return u.toString()}
function parseJson3(j){const seg=[],parts=[];for(const ev of j.events||[]){if(!ev.segs)continue;const s=ev.segs.map(x=>x.utf8||"").join("").replace(/\s+/g," ").trim();if(!s)continue;seg.push({start_ms:ev.tStartMs||0,dur_ms:ev.dDurationMs||0,text:s});parts.push(s)}return{text:parts.join(" ").replace(/\s+/g," ").trim(),segments:seg}}
function parseVtt(v){const seg=[],parts=[];for(const b of String(v).split(/\n\s*\n/)){if(!b.includes("-->"))continue;const lines=b.split(/\r?\n/).filter(Boolean);const i=lines.findIndex(x=>x.includes("-->"));const s=lines.slice(i+1).join(" ").replace(/<[^>]+>/g,"").replace(/\s+/g," ").trim();if(s){seg.push({text:s});parts.push(s)}}return{text:parts.join(" ").replace(/\s+/g," ").trim(),segments:seg}}
function parseXmlCaption(x){const clean=String(x).replace(/<text[^>]*>/g,"\n").replace(/<\/text>/g," ").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim();return{text:clean,segments:clean?[{text:clean}]:[]}}
async function save(env,rec){const id=newId("ytr");const textKey=`youtube/resilient/${id}/text.txt`;const segKey=`youtube/resilient/${id}/segments.json`;const chunks=Math.max(1,Math.ceil(rec.text.length/1200));await kvPut(env.KV,textKey,rec.text);await kvPut(env.KV,segKey,rec.segments||[]);await run(env.DB,"INSERT INTO youtube_transcripts_resilient VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",[id,rec.video_id,rec.url,rec.title||null,rec.language||"en",rec.source_method,textKey,segKey,rec.text.length,chunks,"ready",null,nowIso(),nowIso()]);return{id,chunk_count:chunks}}
async function status(){return{ok:true,worker:WORKER_NAME,version:VERSION,capabilities:["public_caption_capture","browser_helper_page","payload_import","manual_import","job_handoff","storage","search","summary"],helper_path:"/helper"}}
function originFromArgs(args){return args&&args.origin?String(args.origin).replace(/\/$/,""):null}
async function helperInfo(args,origin){return{ok:true,worker:WORKER_NAME,version:VERSION,helper_url:(origin||"https://afo-youtube-transcript-resilient-mcp.jaredtechfit.workers.dev")+"/helper",for_url:args.url||null,steps:["Open the helper page.","Paste the YouTube video URL.","Open the YouTube transcript panel in your browser and copy the visible transcript text.","Paste the transcript text into the helper and submit.","The helper stores the transcript in D1/KV and returns a transcript_id."],stores_with_tool:"submit_browser_caption_payload"}}
async function probe(args){const id=videoId(args.url);if(!id)return{ok:false,error:"Could not extract video_id"};const watch=`https://www.youtube.com/watch?v=${id}`;let title=null;try{const o=await fetch(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(watch)}`);if(o.ok)title=(await o.json()).title||null}catch{}let statusCode=null,visible=[];try{const r=await fetch(watch,{headers:{"user-agent":"Mozilla/5.0 transcript probe","accept-language":`${args.language||"en"},en;q=0.8`}});statusCode=r.status;visible=tracks(await r.text()).map(t=>({languageCode:t.languageCode||null,kind:t.kind||null,name:t.name?t.name.simpleText||null:null,hasBaseUrl:!!t.baseUrl,isTranslatable:!!t.isTranslatable}))}catch(e){return{ok:true,video_id:id,title,watch_status:statusCode,has_public_caption_tracks:false,caption_track_count:0,error:String(e.message||e)}}return{ok:true,video_id:id,title,watch_status:statusCode,has_public_caption_tracks:visible.length>0,caption_track_count:visible.length,caption_tracks:visible}}
async function tryCaption(track){const attempts=["json3","vtt","srv3","ttml"];for(const f of attempts){try{const r=await fetch(fmtUrl(track.baseUrl,f));if(!r.ok)continue;if(f==="json3"){const p=parseJson3(await r.json());if(p.text)return{parsed:p,method:"caption_json3"}}else if(f==="vtt"){const p=parseVtt(await r.text());if(p.text)return{parsed:p,method:"caption_vtt"}}else{const p=parseXmlCaption(await r.text());if(p.text)return{parsed:p,method:"caption_"+f}}}catch{}}
try{const r=await fetch(track.baseUrl);if(r.ok){const raw=await r.text();let p=parseXmlCaption(raw);if(!p.text&&raw.trim().startsWith("WEBVTT"))p=parseVtt(raw);if(p.text)return{parsed:p,method:"caption_default"}}}catch{}return null}
async function capture(env,args){await schema(env);const id=videoId(args.url);if(!id)return{ok:false,error:"Could not extract video_id"};const lang=args.language||"en";if(!args.force){const ex=await first(env.DB,"SELECT id,source_method FROM youtube_transcripts_resilient WHERE video_id=? AND language=? AND status=? ORDER BY created_at DESC LIMIT 1",[id,lang,"ready"]);if(ex)return{ok:true,cached:true,transcript_id:ex.id,video_id:id,source_method:ex.source_method}}
const watch=`https://www.youtube.com/watch?v=${id}`;let statusCode=null;const page=await fetch(watch,{headers:{"user-agent":"Mozilla/5.0 transcript capture","accept-language":`${lang},en;q=0.8`}});statusCode=page.status;const list=tracks(await page.text());if(!list.length)return{ok:false,video_id:id,watch_status:statusCode,error:"No visible public captionTracks found",fallback_tools:["get_browser_capture_helper","submit_browser_caption_payload","import_transcript_text","create_audio_transcription_job"]};const tr=pickTrack(list,lang);const attempt=await tryCaption(tr);if(!attempt||!attempt.parsed||!attempt.parsed.text)return{ok:false,video_id:id,watch_status:statusCode,error:"Caption track found but parsed empty",fallback_tools:["get_browser_capture_helper","submit_browser_caption_payload","import_transcript_text","create_audio_transcription_job"]};const saved=await save(env,{video_id:id,url:watch,title:args.title||null,language:lang,source_method:attempt.method,text:attempt.parsed.text,segments:attempt.parsed.segments});return{ok:true,transcript_id:saved.id,video_id:id,language:lang,source_method:attempt.method,char_count:attempt.parsed.text.length,chunk_count:saved.chunk_count}}
async function payloadImport(env,args){await schema(env);const id=videoId(args.url);if(!id)return{ok:false,error:"Could not extract video_id"};let transcriptText=String(args.text||"").trim();let seg=Array.isArray(args.segments)?args.segments:[];const f=args.payload_format||"plain_text";if(!transcriptText&&args.payload){if(f==="vtt"){const p=parseVtt(args.payload);transcriptText=p.text;seg=p.segments}else if(f==="json3"){const p=parseJson3(JSON.parse(args.payload));transcriptText=p.text;seg=p.segments}else if(f==="segments_json"){seg=JSON.parse(args.payload);transcriptText=(Array.isArray(seg)?seg:[]).map(x=>x.text||"").join(" ").trim()}else transcriptText=String(args.payload).trim()}if(transcriptText.length<5)return{ok:false,error:"No usable transcript text supplied"};const saved=await save(env,{video_id:id,url:`https://www.youtube.com/watch?v=${id}`,title:args.title||null,language:args.language||"en",source_method:"browser_payload",text:transcriptText,segments:seg});return{ok:true,transcript_id:saved.id,video_id:id,source_method:"browser_payload",char_count:transcriptText.length,chunk_count:saved.chunk_count}}
async function manualImport(env,args){await schema(env);const id=videoId(args.url);if(!id)return{ok:false,error:"Could not extract video_id"};const transcriptText=String(args.text||"").trim();if(transcriptText.length<5)return{ok:false,error:"Transcript text too short"};const saved=await save(env,{video_id:id,url:`https://www.youtube.com/watch?v=${id}`,title:args.title||null,language:args.language||"en",source_method:args.source_method||"manual_import",text:transcriptText,segments:[]});return{ok:true,transcript_id:saved.id,video_id:id,char_count:transcriptText.length,chunk_count:saved.chunk_count}}
async function createJob(env,args){await schema(env);const id=videoId(args.url)||null;const job=newId("ytjob");await run(env.DB,"INSERT INTO transcript_jobs_resilient VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",[job,id,args.url,args.language||"en",args.title||null,"queued",args.audio_source_note||"pending",null,null,nowIso(),nowIso()]);return{ok:true,job_id:job,video_id:id,status:"queued",next_tool:"submit_transcription_result"}}
async function submitJob(env,args){await schema(env);if(env.TRANSCRIPTION_WEBHOOK_SECRET&&args.webhook_secret!==env.TRANSCRIPTION_WEBHOOK_SECRET)return{ok:false,error:"Invalid webhook_secret"};const job=await first(env.DB,"SELECT * FROM transcript_jobs_resilient WHERE job_id=?",[args.job_id]);if(!job)return{ok:false,error:"Job not found"};const transcriptText=String(args.text||"").trim();if(transcriptText.length<5)return{ok:false,error:"Transcript text too short"};const saved=await save(env,{video_id:job.video_id,url:job.url,title:args.title||job.title,language:job.language||"en",source_method:args.source_method||"external_transcription",text:transcriptText,segments:Array.isArray(args.segments)?args.segments:[]});await run(env.DB,"UPDATE transcript_jobs_resilient SET status=?, result_transcript_id=?, updated_at=? WHERE job_id=?",["complete",saved.id,nowIso(),args.job_id]);return{ok:true,job_id:args.job_id,transcript_id:saved.id,char_count:transcriptText.length,chunk_count:saved.chunk_count}}
async function getTranscript(env,args){await schema(env);const row=await first(env.DB,"SELECT * FROM youtube_transcripts_resilient WHERE id=?",[args.transcript_id]);if(!row)return{ok:false,error:"Transcript not found"};const out={ok:true,transcript:row};if(args.include_text!==false)out.text=await kvGet(env.KV,row.text_kv_key);if(args.include_segments&&row.segments_kv_key)out.segments=await kvGet(env.KV,row.segments_kv_key);return out}
async function listTranscripts(env,args){await schema(env);const limit=Math.min(Number(args.limit||20),100);let sql="SELECT id,video_id,url,title,language,source_method,char_count,chunk_count,status,created_at,updated_at FROM youtube_transcripts_resilient WHERE 1=1";const p=[];if(args.video_id){sql+=" AND video_id=?";p.push(args.video_id)}if(args.language){sql+=" AND language=?";p.push(args.language)}sql+=" ORDER BY created_at DESC LIMIT ?";p.push(limit);const rows=await all(env.DB,sql,p);return{ok:true,count:rows.length,transcripts:rows}}
async function searchTranscripts(env,args){await schema(env);const q=String(args.query||"").toLowerCase();const rows=await all(env.DB,"SELECT * FROM youtube_transcripts_resilient ORDER BY created_at DESC LIMIT 200");const hits=[];for(const row of rows){if(args.video_id&&row.video_id!==args.video_id)continue;const stored=String(await kvGet(env.KV,row.text_kv_key)||"");const idx=stored.toLowerCase().indexOf(q);if(idx>=0){hits.push({transcript_id:row.id,video_id:row.video_id,title:row.title,source_method:row.source_method,snippet:stored.slice(Math.max(0,idx-200),Math.min(stored.length,idx+500))});if(hits.length>=Math.min(Number(args.top_k||8),25))break}}return{ok:true,query:args.query,count:hits.length,hits}}
async function summarizeTranscript(env,args){await schema(env);const row=await first(env.DB,"SELECT * FROM youtube_transcripts_resilient WHERE id=?",[args.transcript_id]);if(!row)return{ok:false,error:"Transcript not found"};const stored=String(await kvGet(env.KV,row.text_kv_key)||"");const sample=stored.slice(0,Math.min(Number(args.max_chars||5000),12000));return{ok:true,transcript_id:row.id,title:row.title,summary:sample.slice(0,1200)+(stored.length>1200?"...":"")}}
async function handle(name,args,env,ctx,origin){switch(name){case"youtube_resilient_status":return status();case"get_browser_capture_helper":return helperInfo(args,origin);case"probe_youtube_sources":if(!args.url)throw new Error("url required");return probe(args);case"capture_youtube_transcript_resilient":if(!args.url)throw new Error("url required");return capture(env,args);case"submit_browser_caption_payload":if(!args.url)throw new Error("url required");return payloadImport(env,args);case"import_transcript_text":if(!args.url||!args.text)throw new Error("url and text required");return manualImport(env,args);case"create_audio_transcription_job":if(!args.url)throw new Error("url required");return createJob(env,args);case"submit_transcription_result":if(!args.job_id||!args.text)throw new Error("job_id and text required");return submitJob(env,args);case"get_youtube_transcript_resilient":if(!args.transcript_id)throw new Error("transcript_id required");return getTranscript(env,args);case"list_youtube_transcripts_resilient":return listTranscripts(env,args);case"search_youtube_transcripts_resilient":if(!args.query)throw new Error("query required");return searchTranscripts(env,args);case"summarize_youtube_transcript_resilient":if(!args.transcript_id)throw new Error("transcript_id required");return summarizeTranscript(env,args);default:throw new Error("Unknown tool: "+name)}}
function helperHtml(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>YouTube Transcript Helper</title><style>body{font-family:system-ui;margin:24px;max-width:760px}input,textarea,button{font:inherit;width:100%;box-sizing:border-box;margin:8px 0;padding:10px}textarea{min-height:260px}button{background:#2563eb;color:white;border:0;border-radius:8px}pre{white-space:pre-wrap;background:#f3f4f6;padding:12px;border-radius:8px}</style></head><body><h1>YouTube Transcript Helper</h1><p>Paste a YouTube URL and transcript text that is visible to you, then submit it into the MCP store.</p><label>YouTube URL</label><input id="url" placeholder="https://www.youtube.com/watch?v=..."><label>Title optional</label><input id="title"><label>Transcript text</label><textarea id="text" placeholder="Paste transcript text here"></textarea><button id="send">Store transcript</button><pre id="out"></pre><script>document.getElementById('send').onclick=async()=>{const out=document.getElementById('out');out.textContent='Submitting...';const body={jsonrpc:'2.0',id:'helper-'+Date.now(),method:'tools/call',params:{name:'submit_browser_caption_payload',arguments:{url:document.getElementById('url').value,title:document.getElementById('title').value,text:document.getElementById('text').value,payload_format:'plain_text',language:'en'}}};try{const r=await fetch('/',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});out.textContent=JSON.stringify(await r.json(),null,2)}catch(e){out.textContent=String(e)}};</script></body></html>`}
export default{async fetch(request,env,ctx){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});const u=new URL(request.url);if(u.pathname==="/health")return Response.json({status:"ok",worker:WORKER_NAME,version:VERSION},{headers:CORS});if(u.pathname==="/helper")return new Response(helperHtml(),{headers:{...CORS,"content-type":"text/html;charset=utf-8"}});if(request.method!=="POST")return new Response("not found",{status:404,headers:CORS});let body;try{body=await request.json()}catch{return errResp(null,-32700,"Parse error")}const{id,method,params}=body;if(method==="initialize")return rpc(id,{protocolVersion:"2024-11-05",capabilities:{tools:{}},serverInfo:{name:WORKER_NAME,version:VERSION}});if(method==="notifications/initialized")return new Response(null,{status:204,headers:CORS});if(method==="ping")return rpc(id,{});if(method==="tools/list")return rpc(id,{tools:TOOLS});if(method==="tools/call"){try{return tool(id,await handle(params?.name,params?.arguments||{},env,ctx,u.origin))}catch(e){return errResp(id,-32603,"Tool error: "+e.message)}}return errResp(id,-32601,"Method not found: "+method)}};
