const VERSION="0.1.0";
const WORKER_NAME="afo_inventory_read_mcp";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const TOOLS=[
{name:"inventory_read_status",description:"Read-only status for the inventory/read plane.",inputSchema:{type:"object",properties:{},required:[]}},
{name:"list_workers",description:"Read-only list Cloudflare Workers in the configured account.",inputSchema:{type:"object",properties:{},required:[]}},
{name:"get_worker_source",description:"Read-only fetch live Worker source. Does not deploy or mutate.",inputSchema:{type:"object",properties:{script_name:{type:"string"}},required:["script_name"]}},
{name:"inspect_worker_bindings",description:"Read-only inspect Worker bindings/settings. Redacts secret/plain text values.",inputSchema:{type:"object",properties:{script_name:{type:"string"}},required:["script_name"]}},
{name:"get_worker_settings",description:"Read-only fetch sanitized Worker settings.",inputSchema:{type:"object",properties:{script_name:{type:"string"}},required:["script_name"]}},
{name:"write_worker_snapshot_to_github",description:"Read live Worker source/settings/bindings and commit a snapshot bundle to GitHub.",inputSchema:{type:"object",properties:{script_name:{type:"string"},owner:{type:"string"},repo:{type:"string"},branch:{type:"string"},base_path:{type:"string"}},required:["script_name","repo"]}}
];
function j(v,s=200){return Response.json(v,{status:s,headers:CORS})}
function rr(id,result){return j({jsonrpc:"2.0",id,result})}
function tr(id,result){return j({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result,null,2)}]}})}
function er(id,code,message){return j({jsonrpc:"2.0",id,error:{code,message}})}
function ep(path){return path.split("/").map(encodeURIComponent).join("/")}
async function cf(env,method,path,body){if(!env.CF_ACCOUNT_ID)throw new Error("CF_ACCOUNT_ID binding missing");if(!env.CF_API_TOKEN)throw new Error("CF_API_TOKEN binding missing");const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${path}`,{method,headers:{Authorization:`Bearer ${env.CF_API_TOKEN}`,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const json=await res.json();if(!json.success)throw new Error(JSON.stringify(json.errors||json));return json.result}
async function gh(env,method,path,body){if(!env.GITHUB_TOKEN)throw new Error("GITHUB_TOKEN binding missing");const res=await fetch(`https://api.github.com${path}`,{method,headers:{Authorization:`Bearer ${env.GITHUB_TOKEN}`,"Content-Type":"application/json","User-Agent":WORKER_NAME,Accept:"application/vnd.github+json"},body:body===undefined?undefined:JSON.stringify(body)});const text=await res.text();const json=text?JSON.parse(text):{};if(!res.ok)throw new Error(`GitHub HTTP ${res.status}: ${text}`);return json}
function redactBinding(b){const safe={name:b.name,type:b.type};for(const k of ["id","namespace_id","bucket_name","bucket","service","environment","index_name"]){if(b[k]!==undefined)safe[k]=b[k]}if(b.type==="plain_text"||b.type==="secret_text"){safe.value_present=Boolean(b.text||b.value||b.name);safe.value_redacted=true}return safe}
function sanitizeSettings(settings){const copy=JSON.parse(JSON.stringify(settings||{}));copy.bindings=(copy.bindings||[]).map(redactBinding);return copy}
async function sha256(text){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return "sha256:"+[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function getSource(args,env){if(!args.script_name)throw new Error("script_name is required");const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/workers/scripts/${args.script_name}/content`,{headers:{Authorization:`Bearer ${env.CF_API_TOKEN}`}});if(!res.ok)throw new Error(`HTTP ${res.status}: ${await res.text()}`);const source=await res.text();return{script_name:args.script_name,source,source_sha256:await sha256(source),size_bytes:new TextEncoder().encode(source).length}}
async function getSettings(args,env){if(!args.script_name)throw new Error("script_name is required");const settings=await cf(env,"GET",`/workers/scripts/${args.script_name}/settings`);return{script_name:args.script_name,read_only:true,settings:sanitizeSettings(settings)}}
async function inspectBindings(args,env){if(!args.script_name)throw new Error("script_name is required");const settings=await cf(env,"GET",`/workers/scripts/${args.script_name}/settings`);const bindings=(settings.bindings||[]).map(redactBinding);const targets=["ADMIN_KEY","DB","ASSISTANT_SYSTEM_PROMPT","AFO_ASSISTANT_MODEL","AFO_ASSISTANT_PROVIDER","SITE_CONTENT","CCS_MICRO_SEO_SITE"];return{schema:"afo.bindings.snapshot.v1",script_name:args.script_name,captured_at:new Date().toISOString(),read_only:true,binding_count:bindings.length,bindings,binding_names:bindings.map(b=>b.name),has_bindings:Object.fromEntries(targets.map(n=>[n,bindings.some(b=>b.name===n)]))}}
async function commitFile(env,{owner,repo,branch="main",path,content,message}){const actualOwner=owner||env.DEFAULT_OWNER||"nothinginfinity";let sha;try{sha=(await gh(env,"GET",`/repos/${actualOwner}/${repo}/contents/${ep(path)}?ref=${encodeURIComponent(branch)}`)).sha}catch(_){}const out=await gh(env,"PUT",`/repos/${actualOwner}/${repo}/contents/${ep(path)}`,{message,content:btoa(unescape(encodeURIComponent(content))),branch,sha});return{path,commit_sha:out.commit&&out.commit.sha,html_url:out.commit&&out.commit.html_url}}
async function writeSnapshot(args,env){const owner=args.owner||env.DEFAULT_OWNER||"nothinginfinity",branch=args.branch||"main",base=args.base_path||`state/cloudflare/workers/${args.script_name}`;const source=await getSource(args,env),settings=await getSettings(args,env),bindings=await inspectBindings(args,env);const worker={schema:"afo.worker.snapshot.v1",script_name:args.script_name,captured_at:new Date().toISOString(),source_path:`${base}/source.worker.js`,source_sha256:source.source_sha256,settings_path:`${base}/settings.snapshot.json`,bindings_path:`${base}/bindings.snapshot.json`};const files=[[`${base}/source.worker.js`,source.source],[`${base}/settings.snapshot.json`,JSON.stringify(settings,null,2)],[`${base}/bindings.snapshot.json`,JSON.stringify(bindings,null,2)],[`${base}/worker.snapshot.json`,JSON.stringify(worker,null,2)]];const commits=[];for(const [path,content] of files){commits.push(await commitFile(env,{owner,repo:args.repo,branch,path,content,message:`Snapshot ${args.script_name}: ${path}`}))}return{ok:true,owner,repo:args.repo,branch,base_path:base,files:commits}}
async function dispatch(name,args,env){if(name==="inventory_read_status")return{worker:WORKER_NAME,version:VERSION,status:"ok",plane:"inventory_read",read_only_cloudflare:true,bindings:{CF_ACCOUNT_ID:Boolean(env.CF_ACCOUNT_ID),CF_API_TOKEN:Boolean(env.CF_API_TOKEN),GITHUB_TOKEN:Boolean(env.GITHUB_TOKEN),DEFAULT_OWNER:Boolean(env.DEFAULT_OWNER)},tools:TOOLS.map(t=>t.name)};if(name==="list_workers"){const r=await cf(env,"GET","/workers/scripts");return{count:r.length,workers:r.map(w=>({id:w.id,created_on:w.created_on,modified_on:w.modified_on,etag:w.etag}))}}if(name==="get_worker_source")return getSource(args,env);if(name==="get_worker_settings")return getSettings(args,env);if(name==="inspect_worker_bindings")return inspectBindings(args,env);if(name==="write_worker_snapshot_to_github")return writeSnapshot(args,env);throw new Error(`Unknown tool: ${name}`)}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});if(request.method==="GET")return j({worker:WORKER_NAME,version:VERSION,status:"ok",tools:TOOLS.map(t=>t.name)});if(request.method!=="POST")return j({error:"POST /mcp required"},405);let p;try{p=await request.json()}catch{return er(null,-32700,"Invalid JSON")}const{id=null,method,params={}}=p;try{if(method==="initialize")return rr(id,{protocolVersion:"2024-11-05",serverInfo:{name:WORKER_NAME,version:VERSION},capabilities:{tools:{}}});if(method==="tools/list")return rr(id,{tools:TOOLS});if(method==="tools/call")return tr(id,await dispatch(params.name,params.arguments||{},env));return er(id,-32601,`Method not found: ${method}`)}catch(e){return er(id,-32603,`Tool error: ${e.message}`)}}};
