const VERSION="0.1.0";
const WORKER_NAME="afo-feed-discoverer-worker";
const PRODUCT_NAME="AFO Feed Discoverer Worker";
const POLICY="Only retrieves public, user-provided, or explicitly authorized content. Does not bypass login, paywalls, CAPTCHAs, access controls, or private content.";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,Mcp-Session-Id"};
const TOOLS=[
{name:"feed_discoverer_status",description:"Health check for the specialized AFO Feed Discoverer Worker.",inputSchema:{type:"object",properties:{},required:[]}},
{name:"discover_public_feeds",description:"Discover RSS, Atom, JSON Feed, sitemap, and podcast feed candidates from a public URL.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},include_common_paths:{type:"boolean",default:true},job_id:{type:"string"},query:{type:"string"}}}},
{name:"run_feed_discovery_job",description:"Run the feed discovery role as one step in the shared Discovery Mode database.",inputSchema:{type:"object",required:["url"],properties:{url:{type:"string"},query:{type:"string"},job_id:{type:"string"},include_common_paths:{type:"boolean",default:true}}}},
{name:"list_recent_feed_discoveries",description:"List recently indexed feed discovery rows from the shared discovery index.",inputSchema:{type:"object",properties:{limit:{type:"number",default:25}},required:[]}}
];
function nowIso(){return new Date().toISOString()}
function newId(prefix){return prefix+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
function rpc(id,result){return Response.json({jsonrpc:"2.0",id,result},{headers:CORS})}
function errResp(id,code,message){return Response.json({jsonrpc:"2.0",id,error:{code,message}},{headers:CORS})}
function tool(id,result){return rpc(id,{content:[{type:"text",text:JSON.stringify(result,null,2)}]})}
async function run(db,sql,params=[]){return db.prepare(sql).bind(...params).run()}
async function first(db,sql,params=[]){return db.prepare(sql).bind(...params).first()}
async function all(db,sql,params=[]){const r=await db.prepare(sql).bind(...params).all();return r.results||[]}
async function kvPut(kv,key,value){await kv.put(key,typeof value==="string"?value:JSON.stringify(value))}
async function kvGet(kv,key){const v=await kv.get(key);if(v===null)return null;try{return JSON.parse(v)}catch{return v}}
async function schema(env){await run(env.DB,"CREATE TABLE IF NOT EXISTS discovery_index (id TEXT PRIMARY KEY, url TEXT UNIQUE, title TEXT, source_type TEXT, capture_type TEXT, first_query TEXT, view_count INTEGER DEFAULT 0, download_count INTEGER DEFAULT 0, capture_count INTEGER DEFAULT 0, last_action TEXT, last_seen_at TEXT, created_at TEXT)");await run(env.DB,"CREATE INDEX IF NOT EXISTS idx_discovery_index_seen ON discovery_index(last_seen_at)");await run(env.DB,"CREATE INDEX IF NOT EXISTS idx_discovery_index_type ON discovery_index(source_type)");await run(env.DB,"CREATE TABLE IF NOT EXISTS discovery_receipts (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, payload_kv_key TEXT, created_at TEXT)");await run(env.DB,"CREATE TABLE IF NOT EXISTS discovery_jobs (id TEXT PRIMARY KEY, query TEXT, seed_url TEXT, mode TEXT, status TEXT, current_step TEXT, worker_plan_kv_key TEXT, result_kv_key TEXT, created_at TEXT, updated_at TEXT)");await run(env.DB,"CREATE TABLE IF NOT EXISTS discovery_job_steps (id TEXT PRIMARY KEY, job_id TEXT, step_order INTEGER, worker_role TEXT, tool_name TEXT, status TEXT, input_kv_key TEXT, output_kv_key TEXT, created_at TEXT, updated_at TEXT)")}
function normUrl(u){try{const x=new URL(String(u));x.hash="";return x.toString()}catch{return String(u||"").trim()}}
function absUrl(base,href){try{return new URL(href,base).toString()}catch{return href}}
function decodeHtml(s){return String(s||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
function stripTags(html){return decodeHtml(String(html||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," "))}
function attr(tag,name){const m=String(tag||"").match(new RegExp(`${name}=["']([^"']+)["']`,`i`));return m?decodeHtml(m[1]):null}
function meta(html,name){const n=String(name).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const m=String(html).match(new RegExp(`<meta[^>]+(?:property|name)=["']${n}["'][^>]+content=["']([^"']*)["'][^>]*>`,`i`))||String(html).match(new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${n}["'][^>]*>`,`i`));return m?decodeHtml(m[1]):null}
function titleOf(html){const og=meta(html,"og:title");if(og)return og;const m=String(html||"").match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?decodeHtml(stripTags(m[1])):null}
async function fetchText(url,accept="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"){const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 AFO public feed discovery","accept-language":"en-US,en;q=0.8","accept":accept}});const text=await r.text();return{ok:r.ok,status:r.status,headers:Object.fromEntries(r.headers),text,url}}
function classifySource(src){const u=(src.url||"").toLowerCase(),t=(src.type||"").toLowerCase(),k=(src.kind||"").toLowerCase();if(k.includes("sitemap")||u.endsWith("sitemap.xml")||t.includes("sitemap"))return"sitemap";if(t.includes("atom")||u.includes("atom"))return"atom_feed";if(t.includes("json")||u.includes("json"))return"json_feed";if(t.includes("rss")||u.includes("rss")||u.includes("feed")||u.includes("podcast")||k.includes("feed"))return"rss_feed";return"html_metadata"}
function feedLinksFromHtml(html,base){const out=[];const re=/<link[^>]+>/gi;let m;while((m=re.exec(String(html||"")))){const tag=m[0],rel=attr(tag,"rel")||"",type=attr(tag,"type")||"",href=attr(tag,"href"),title=attr(tag,"title")||null;if(!href)continue;if(/alternate|feed/i.test(rel)||/rss|atom|json\+feed|xml/i.test(type)){const src={url:absUrl(base,href),rel,type,title,kind:"feed",source:"html_link"};src.source_type=classifySource(src);out.push(src)}}return out}
async function discoverPublicFeeds(args){const url=normUrl(args.url);const found=[];let page={};try{const r=await fetchText(url);page={status:r.status,title:titleOf(r.text),content_type:r.headers["content-type"]||null};if(/xml|rss|atom|feed/i.test(page.content_type||"")){found.push({url,rel:"self",type:page.content_type,title:page.title,kind:"feed",source:"self"})}found.push(...feedLinksFromHtml(r.text,url))}catch(e){page={error:String(e.message||e)}}if(args.include_common_paths!==false){try{const root=new URL(url).origin;for(const p of ["/feed","/feed/","/rss","/rss.xml","/atom.xml","/feed.xml","/podcast.xml","/sitemap.xml"]){found.push({url:root+p,rel:"common_path",type:p.includes("sitemap")?"sitemap":"feed",title:null,kind:p.includes("sitemap")?"sitemap":"feed",source:"common_path_guess"})}}catch{}}
const feeds=[],seen=new Set();for(const f of found){if(!f.url||seen.has(f.url))continue;seen.add(f.url);f.source_type=f.source_type||classifySource(f);feeds.push(f)}return{ok:true,worker:WORKER_NAME,version:VERSION,url,feed_count:feeds.length,feeds,metadata:page,policy:POLICY}}
async function saveReceipt(env,r){await schema(env);const key=`receipts/${r.receipt_id}.json`;await kvPut(env.KV,key,r);try{await run(env.DB,"INSERT OR REPLACE INTO discovery_receipts VALUES (?, ?, ?, ?, ?)",[r.receipt_id,r.kind,r.subject||null,key,r.created_at||nowIso()])}catch{}return r}
function receipt(kind,extra={}){return{receipt_id:newId("rcpt"),kind,worker:WORKER_NAME,version:VERSION,created_at:nowIso(),policy:POLICY,...extra}}
async function upsertIndexItem(env,item,query,action="view"){await schema(env);const url=item.url||"unknown";const title=item.title||item.url||item.source_type||"Untitled source";const source_type=item.source_type||classifySource(item);const existing=await first(env.DB,"SELECT id FROM discovery_index WHERE url=?",[url]);const id=existing?.id||newId("idx");if(existing){await run(env.DB,"UPDATE discovery_index SET title=COALESCE(?,title), source_type=COALESCE(?,source_type), view_count=view_count+1, last_action=?, last_seen_at=? WHERE url=?",[title,source_type,action,nowIso(),url])}else{await run(env.DB,"INSERT OR REPLACE INTO discovery_index VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",[id,url,title,source_type,null,query||null,1,0,0,action,nowIso(),nowIso()])}return{id,url,title,source_type}}
async function saveJobStep(env,job_id,order,input,output){if(!job_id)return null;await schema(env);const id=newId("step");const inKey=`jobs/${job_id}/feed-discoverer-input.json`;const outKey=`jobs/${job_id}/feed-discoverer-output.json`;await kvPut(env.KV,inKey,input);await kvPut(env.KV,outKey,output);await run(env.DB,"INSERT OR REPLACE INTO discovery_job_steps VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",[id,job_id,order||3,"feed_discoverer","discover_public_feeds","ok",inKey,outKey,nowIso(),nowIso()]);await run(env.DB,"UPDATE discovery_jobs SET current_step=?, updated_at=? WHERE id=?",["feed_discoverer",nowIso(),job_id]);return{id,job_id,step_order:order||3}}
async function runFeedDiscoveryJob(env,args){const result=await discoverPublicFeeds(args);const indexed=[];for(const feed of result.feeds||[]){indexed.push(await upsertIndexItem(env,feed,args.query||args.url,"feed_discovered"))}const r=await saveReceipt(env,receipt("feed_discovery",{subject:args.url,url:args.url,query:args.query||null,feed_count:result.feed_count,indexed_count:indexed.length,feeds:indexed.slice(0,50)}));const step=await saveJobStep(env,args.job_id,3,args,{...result,receipt_id:r.receipt_id,indexed_count:indexed.length});return{...result,indexed_count:indexed.length,discovery_receipt:r,job_step:step}}
async function listRecent(env,args={}){await schema(env);const rows=await all(env.DB,"SELECT * FROM discovery_index WHERE source_type IN ('rss_feed','atom_feed','json_feed','sitemap') ORDER BY last_seen_at DESC LIMIT ?",[Math.min(Number(args.limit||25),100)]);return{ok:true,count:rows.length,items:rows,policy:POLICY}}
async function handle(name,args,env){switch(name){case"feed_discoverer_status":return{ok:true,product:PRODUCT_NAME,worker:WORKER_NAME,version:VERSION,role:"feed_discoverer",shared_database:true,tables:["discovery_index","discovery_receipts","discovery_jobs","discovery_job_steps"],policy:POLICY};case"discover_public_feeds":if(!args.url)throw new Error("url required");return discoverPublicFeeds(args);case"run_feed_discovery_job":if(!args.url)throw new Error("url required");return runFeedDiscoveryJob(env,args);case"list_recent_feed_discoveries":return listRecent(env,args);default:throw new Error("Unknown tool: "+name)}}
function html(result){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${PRODUCT_NAME}</title><style>body{font-family:system-ui;margin:24px;background:#f8fafc;color:#0f172a}main{max-width:980px;margin:auto}.hero{background:#0f172a;color:white;padding:24px;border-radius:22px}.card{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:14px;margin:12px 0}a{color:#1d4ed8;font-weight:800}pre{background:#020617;color:#e2e8f0;padding:14px;border-radius:14px;overflow:auto}</style></head><body><main><section class="hero"><h1>${PRODUCT_NAME}</h1><p>Specialized Discovery Mode worker: feed_discoverer. Shared database compatible.</p><form action="/run" method="GET"><input name="url" placeholder="https://example.com" style="width:70%;padding:12px;border-radius:10px;border:0"><button style="padding:12px;border-radius:10px">Discover Feeds</button></form></section>${(result?.feeds||result?.items||[]).map(x=>`<div class="card"><a href="${x.url}" target="_blank">${x.title||x.url}</a><div>${x.source_type||""}</div></div>`).join("")}<pre>${JSON.stringify(result||{ok:true,worker:WORKER_NAME,version:VERSION},null,2)}</pre></main></body></html>`}
export default{async fetch(request,env,ctx){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});const u=new URL(request.url);if(u.pathname==="/health")return Response.json({ok:true,worker:WORKER_NAME,version:VERSION,policy:POLICY},{headers:CORS});if(request.method==="GET"&&(u.pathname==="/"||u.pathname==="/console"))return new Response(html(null),{headers:{...CORS,"content-type":"text/html;charset=utf-8"}});if(request.method==="GET"&&u.pathname==="/run"){const result=await runFeedDiscoveryJob(env,{url:u.searchParams.get("url"),query:u.searchParams.get("query")||u.searchParams.get("url")});return new Response(html(result),{headers:{...CORS,"content-type":"text/html;charset=utf-8"}})}if(request.method!=="POST")return new Response("not found",{status:404,headers:CORS});let body;try{body=await request.json()}catch{return errResp(null,-32700,"Parse error")}const{id,method,params}=body;if(method==="initialize")return rpc(id,{protocolVersion:"2024-11-05",capabilities:{tools:{}},serverInfo:{name:WORKER_NAME,version:VERSION}});if(method==="notifications/initialized")return new Response(null,{status:204,headers:CORS});if(method==="tools/list")return rpc(id,{tools:TOOLS});if(method==="tools/call"){try{return tool(id,await handle(params?.name,params?.arguments||{},env))}catch(e){return errResp(id,-32603,"Tool error: "+e.message)}}return errResp(id,-32601,"Method not found: "+method)}};
