const VERSION="0.2.0-apply-preserve-existing";
const WORKER_NAME="afo_cloudflare_apply_mcp";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const TOOLS=[
  {name:"apply_status",description:"Status for Cloudflare apply plane v1. Mutations require confirm_apply=true.",inputSchema:{type:"object",properties:{},required:[]}},
  {name:"validate_apply_plan",description:"Validate that a Cloudflare apply plan is structurally ready.",inputSchema:{type:"object",properties:{plan:{type:"object"}},required:["plan"]}},
  {name:"explain_apply_requirements",description:"Explain required bindings and confirmations before a Cloudflare apply operation can run.",inputSchema:{type:"object",properties:{plan:{type:"object"}},required:[]}},
  {name:"apply_worker_binding_plan_preserve_existing",description:"Apply a worker binding patch plan by fetching live source/settings, preserving existing bindings internally, merging add_or_update, and redeploying. Requires confirm_apply=true.",inputSchema:{type:"object",properties:{plan:{type:"object"},script_content:{type:"string"},confirm_apply:{type:"boolean"}},required:["plan","confirm_apply"]}}
];
function j(v,s=200){return Response.json(v,{status:s,headers:CORS})}
function rr(id,result){return j({jsonrpc:"2.0",id,result})}
function tr(id,result){return j({jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(result,null,2)}]}})}
function er(id,c,m){return j({jsonrpc:"2.0",id,error:{code:c,message:m}})}
function sanitizeBinding(b){const safe={name:b.name,type:b.type};for(const k of ["id","namespace_id","bucket_name","bucket","service","environment","index_name"]){if(b[k]!==undefined)safe[k]=b[k]}if(b.type==="plain_text"||b.type==="secret_text"){safe.value_present=Boolean(b.text||b.value||b.name);safe.value_redacted=true}return safe}
function toCfBinding(b){if(b.type==="r2_bucket")return{type:"r2_bucket",name:b.name,bucket_name:b.bucket_name||b.bucket||b.id};if(b.type==="d1")return{type:"d1",name:b.name,id:b.id};if(b.type==="kv_namespace")return{type:"kv_namespace",name:b.name,namespace_id:b.namespace_id||b.id};if(b.type==="service")return{type:"service",name:b.name,service:b.service||b.id,environment:b.environment||"production"};if(b.type==="plain_text")return{type:"plain_text",name:b.name,text:b.value||b.text||""};if(b.type==="secret_text")return{type:"secret_text",name:b.name,text:b.value||b.text||""};if(b.type==="ai")return{type:"ai",name:b.name};if(b.type==="vectorize")return{type:"vectorize",name:b.name,index_name:b.index_name||b.id};return b}
function buildMultipart(scriptContent,bindings){const boundary=`----AfoApply${crypto.randomUUID().replaceAll("-","")}`;const metadata=JSON.stringify({main_module:"worker.js",usage_model:"standard",bindings:(bindings||[]).map(toCfBinding)});const body=[`--${boundary}`,'Content-Disposition: form-data; name="metadata"',"Content-Type: application/json","",metadata,`--${boundary}`,'Content-Disposition: form-data; name="worker.js"; filename="worker.js"',"Content-Type: application/javascript+module","",scriptContent,`--${boundary}--`].join("\r\n");return{body,boundary}}
async function cfJson(env,method,path,body){if(!env.CF_ACCOUNT_ID)throw new Error("CF_ACCOUNT_ID binding missing");if(!env.CF_API_TOKEN)throw new Error("CF_API_TOKEN binding missing");const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${path}`,{method,headers:{Authorization:`Bearer ${env.CF_API_TOKEN}`,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const text=await res.text();const json=text?JSON.parse(text):{};if(!res.ok||!json.success)throw new Error(`Cloudflare API ${res.status}: ${text}`);return json.result}
async function fetchWorkerSource(env,scriptName){if(!env.CF_ACCOUNT_ID)throw new Error("CF_ACCOUNT_ID binding missing");if(!env.CF_API_TOKEN)throw new Error("CF_API_TOKEN binding missing");const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/workers/scripts/${scriptName}/content`,{headers:{Authorization:`Bearer ${env.CF_API_TOKEN}`}});const text=await res.text();if(!res.ok)throw new Error(`Could not fetch live Worker source: HTTP ${res.status}: ${text.slice(0,300)}`);return text}
async function deployWorker(env,scriptName,scriptContent,bindings){const mp=buildMultipart(scriptContent,bindings);const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/workers/scripts/${scriptName}`,{method:"PUT",headers:{Authorization:`Bearer ${env.CF_API_TOKEN}`,"Content-Type":`multipart/form-data; boundary=${mp.boundary}`},body:mp.body});const text=await res.text();let json={};try{json=text?JSON.parse(text):{}}catch{json={raw:text}}if(!res.ok||!json.success)throw new Error(`Cloudflare deploy failed ${res.status}: ${text}`);return json.result}
function validatePlan(plan){const errors=[];if(!plan||typeof plan!=="object")errors.push("plan object is required");if(plan&&!plan.schema)errors.push("plan.schema missing");if(plan&&plan.plan_type!=="worker_binding_patch")errors.push("plan.plan_type must be worker_binding_patch");if(plan&&!plan.script_name)errors.push("plan.script_name missing");if(plan&&plan.preserve_existing!==true)errors.push("plan.preserve_existing must be true");if(plan&&!Array.isArray(plan.add_or_update))errors.push("plan.add_or_update must be array");if(plan&&(plan.remove||[]).length)errors.push("remove operations are not supported by this v1 apply tool");return{valid:errors.length===0,errors,plan_type:plan&&plan.plan_type||null,script_name:plan&&plan.script_name||null}}
async function applyBindingPlan(args,env){const plan=args.plan||{};const validation=validatePlan(plan);if(!validation.valid)throw new Error(`Invalid plan: ${validation.errors.join("; ")}`);if(args.confirm_apply!==true)throw new Error("confirm_apply=true is required");const scriptName=plan.script_name;const scriptContent=args.script_content&&args.script_content.trim()?args.script_content:await fetchWorkerSource(env,scriptName);if(!scriptContent||scriptContent.length<20)throw new Error("script content unavailable or too small; refusing to deploy");const settings=await cfJson(env,"GET",`/workers/scripts/${scriptName}/settings`);const existing=settings.bindings||[];const updates=(plan.add_or_update||[]).map(toCfBinding);const names=new Set(updates.map(b=>b.name));const merged=[...existing.filter(b=>!names.has(b.name)),...updates];await deployWorker(env,scriptName,scriptContent,merged);return{ok:true,applied:true,script_name:scriptName,plan_id:plan.plan_id||null,plan_hash:plan.plan_hash||null,preserved_count:existing.filter(b=>!names.has(b.name)).length,updated_count:updates.length,total_bindings:merged.length,bindings:merged.map(sanitizeBinding),applied_at:new Date().toISOString(),audit_next:"Run inventory_read.inspect_worker_bindings, then audit_receipt.verify_bindings_match_plan and write_audit_receipt."}}
async function dispatch(name,args,env){if(name==="apply_status")return{worker:WORKER_NAME,version:VERSION,status:"ok",mode:"gated_apply_v1",plane:"cloudflare_apply",writes_cloudflare:true,mutation_tools_enabled:true,bindings:{CF_ACCOUNT_ID:Boolean(env.CF_ACCOUNT_ID),CF_API_TOKEN:Boolean(env.CF_API_TOKEN)},tools:TOOLS.map(t=>t.name)};if(name==="validate_apply_plan")return validatePlan(args.plan);if(name==="explain_apply_requirements")return{plane:"cloudflare_apply",mode:"gated_apply_v1",required:["CF_ACCOUNT_ID","CF_API_TOKEN","plan.plan_type=worker_binding_patch","plan.preserve_existing=true","confirm_apply=true"],policy:["fetch live source/settings internally","merge by binding name","do not return plaintext/secret values","fail closed if source/settings cannot be fetched","no remove operations in v1"],plan_validation:args.plan?validatePlan(args.plan):null};if(name==="apply_worker_binding_plan_preserve_existing")return applyBindingPlan(args,env);throw new Error(`Unknown tool: ${name}`)}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});if(request.method==="GET")return j({worker:WORKER_NAME,version:VERSION,status:"ok",mode:"gated_apply_v1",tools:TOOLS.map(t=>t.name)});if(request.method!=="POST")return j({error:"POST /mcp required"},405);let p;try{p=await request.json()}catch{return er(null,-32700,"Invalid JSON")}const{id=null,method,params={}}=p;try{if(method==="initialize")return rr(id,{protocolVersion:"2024-11-05",serverInfo:{name:WORKER_NAME,version:VERSION},capabilities:{tools:{}}});if(method==="tools/list")return rr(id,{tools:TOOLS});if(method==="tools/call")return tr(id,await dispatch(params.name,params.arguments||{},env));return er(id,-32601,`Method not found: ${method}`)}catch(e){return er(id,-32603,`Tool error: ${e.message}`)}}};
